version: '3.1'

services:
  state-sync:
    # build: ./state-sync
    image: "ghcr.io/csenet/qusahaiel/state-sync:latest"
    container_name: jphacks_state-sync
    ports:
      - "8080:8080"

  kusa-api:
    # build: ./back
    image: "ghcr.io/csenet/qusahaiel/kusa-api:latest"
    container_name: jphacks_kusa-api
    ports:
      - "8000:8000"

  front:
    # build: ./front
    image: "ghcr.io/csenet/qusahaiel/front:latest"
    container_name: jphacks_front
    ports:
      - "3000:3000"
