apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.26.1 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.front.entrypoints: web
    traefik.http.routers.front.rule: PathPrefix(`/`)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yml convert
        kompose.version: 1.26.1 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.front.entrypoints: web
        traefik.http.routers.front.rule: PathPrefix(`/`)
      creationTimestamp: null
      labels:
        io.kompose.service: front
    spec:
      containers:
        - image: ghcr.io/csenet/qusahaiel/front:latest
          name: jphacks-front
          resources: {}
      restartPolicy: Always
status: {}
