apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: app

spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: front
            port:
              number: 80
      - path: /grass
        pathType: Exact
        backend:
          service:
            name: kusa-api
            port:
              number: 80
      - path: /state
        pathType: Exact
        backend:
          service:
            name: state-sync
            port:
              number: 80